#!/usr/bin/env python
# -*- mode: python -*-

"""Convert simplified dot (sdot file) to dot format.
Simpler dot format is
from -> to
from -> to
"""

import sys
import re

def usage():
    "print usage"
    print "simpler_dot input.sdot output.dot"

def dot_node_name(name):
    "create a node name which is safe in dot lang"
    return name.replace(" ", "").lower()

def convert(from_file, output_file):
    "convert sdot format to dot format"
    nodes = set()
    edges = []
    with open(from_file) as inputf:
        with open(output_file, "w") as outputf:
            outputf.write("digraph simple {\n")
            for line in inputf.readlines():
                match_result = re.match(r"(.*)[\s]*->[\s]*(.*)", line)
                if not match_result:
                    raise Exception("{0} looks illegal format".format(line))
                from_node_name = match_result.group(1).strip()
                to_node_name = match_result.group(2).strip()
                nodes.add(from_node_name)
                nodes.add(to_node_name)
                edges.append((from_node_name, to_node_name))
            for node in nodes:
                outputf.write('  {0} [label="{1}"];\n'.format(dot_node_name(node), node))
            for from_node, to_node in edges:
                outputf.write('  {0} -> {1};\n'.format(dot_node_name(from_node),
                                                       dot_node_name(to_node)))
            outputf.write("}\n")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        usage()
        sys.exit()
    convert(*sys.argv[1:])
